# Generated by Django 5.1.7 on 2025-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_promotion",
            field=models.BooleanField(default=False),
        ),
    ]
