# Generated by Django 5.1.7 on 2025-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0002_product_is_promotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discounted_price",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
